---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-admission-controller
  namespace: sysdig-admission-controller
spec:
  chart:
    spec:
      chart: admission-controller
      # On prod clusters we want to have a specific version of sysdig-deploy chart
      version: 0.6.24
  values:
    clusterName: prod-1
