---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-deploy
  namespace: sysdig-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: sysdig-deploy
      sourceRef:
        kind: HelmRepository
        name: sysdig-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      sysdig:
        accessKeySecret: "sysdig-agent"
        region: "eu1"
      image:
        registry: quay.io

    agent:
      enabled: true
      sysdig:
        settings:
          app_checks_enabled: false
          feature:
            mode: monitor
          jmx:
            enabled: false

    nodeAnalyzer:
      enabled: true

    rapidResponse:
      enabled: false