---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-deploy
  namespace: sysdig-agent
spec:
  chart:
    spec:
      chart: sysdig-deploy
      version: ">= 1.3.20"
  values:
    global:
      clusterConfig:
        name: "k8s-daniele-vms"
      sysdig:
        region: "us1"

    agent:
      image:
        tag: 12.8.1
      enabled: true
      resourceProfile: custom
      resources:
        requests:
          cpu: 300m
          memory: 600Mi
        limits:
          cpu: 500m
          memory: 1Gi
      sysdig:
        settings:
          prometheus:
            enabled: true
            prom_service_discovery: true

    nodeAnalyzer:
      nodeAnalyzer:
        benchmarkRunner:
        runtimeScanner:
          deploy: true
          settings:
            eveEnabled: true
      secure:
        vulnerabilityManagement:
          newEngineOnly: true

    rapidResponse:
      enabled: true
      rapidResponse:
        existingPassphraseSecret: "sysdig-rapid-response"
