---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-admission-controller
  namespace: sysdig-admission-controller
spec:
  chart:
    spec:
      chart: admission-controller
      # On dev clusters we want to automatically have the latest version of the chart
      version: ">=0.6.24"
  values:
    clusterName: dev-2
